[package]
published-at = "0x18318e2e29abff84cab26ec9358466455d0e73c4dd875e8528239fc5fc67c664"
name = "Dubhe"
edition = "2024"
version = "1.0.0"
license = "apache2.0"
authors = ["Obelisk Labs"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.46.3" }

[addresses]
dubhe = "0x18318e2e29abff84cab26ec9358466455d0e73c4dd875e8528239fc5fc67c664"

