[package]
published-at = "0x9a80b0aa328dc6239340aa0af1c82accbc4992096ea894f19cfb2f3704d66d02"
name = "Dubhe"
edition = "2024"
version = "1.0.0"
license = "apache2.0"
authors = ["Obelisk Labs"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.46.3" }

[addresses]
dubhe = "0x9a80b0aa328dc6239340aa0af1c82accbc4992096ea894f19cfb2f3704d66d02"

